ATTEMPT at fixing compiled binaries
````
$ (cd dist/linux; ./DarkChess)
Traceback (most recent call last):
  File "DarkChess/__main__.py", line 11, in <module>
ImportError: attempted relative import with no known parent package
Failed to execute script '__main__' due to unhandled exception!
```